version: "3.0"
services:
  timestamp:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "timestamp"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      TIMESTAMP_LABEL: "date"
      FORMAT: "%d-%b-%Y"
      TIMEZONE: "CET"
    ports:
      - 80:80
